url: 
baseurl: "" 

# Site settings
title: Col·lectivaT
email: info@collectivat.cat
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Özgür Güneş Öztürk Okumuş
  pic: 1
  position: Dynamizer of Research and Consulting
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Pelin Doğan
  pic: 2
  position: Dynamizer of Language Services
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Baybars Külebi
  pic: 3
  position: Dynamizer of Technology
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Federica Capranico
  pic: 4
  position: Business Intelligence Expert
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Alp Öktem
  pic: 5
  position: Computational Linguistics Expert
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/collectivat
  - title: facebook
    url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/collectivat
  - title: github
    url: http://github.com/collectivat

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
